default_platform(:android)

platform :android do
  desc "Firebase App Distribution Beta Testing"
  lane :upload_firebase_app_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    release = firebase_app_distribution(
      app: "1:957768416946:android:3c2a69284122d21e8e13ab",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "ferasdev@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
    )
  end
end
